all:	str memory smartPtr ptr1 ptr2 rat

str:
	c++ -o str -O3 -std=c++11 str.cpp
memory:
	c++ -o memory -O3 -std=c++11 memory.cpp
smartPtr:
	c++ -o smartPtr -O3 -std=c++11 smartPtr.cpp
ptr1:
	c++ -o ptr1 -O3 -std=c++11 ptr1.cpp
ptr2:
	c++ -o ptr2 -O3 -std=c++11 ptr2.cpp
rat:
	c++ -o rat -O3 -std=c++11 rat.cpp rational.cpp
clean:	
	rm str memory smartPtr ptr1 ptr2 rat
